version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sysml2
      POSTGRES_USER: sysml2
      POSTGRES_PASSWORD: sysml2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/systems-modeling/sysml-v2-api-services:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/sysml2
      SPRING_DATASOURCE_USERNAME: sysml2
      SPRING_DATASOURCE_PASSWORD: sysml2
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9000/docs || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgres-data:
